sentry:
  dsn: "%env(SENTRY_DSN)%"
  register_error_listener: false
  options:
    environment: '%kernel.environment%'
    #release: '%env(VERSION)%' #your app version
    error_types: E_ALL & ~E_NOTICE & ~E_DEPRECATED
