sentry:
  dsn: "%env(SENTRY_DSN)%"
  register_error_listener: false
  options:
    environment: '%kernel.environment%'
    release: '%ferienpass.version%'
    error_types: E_ALL & ~E_NOTICE & ~E_DEPRECATED
  tracing:
    dbal:
      # See <https://github.com/getsentry/sentry-symfony/issues/483>
      enabled: false
