name: Monorepo UX Split

on:
  push:
    tags:
      - '*'
    branches:
      - 3.x

jobs:
  monorepo-split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - 'Theme'
          - 'Host{0}Portal'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: previous_tag
        if: github.ref != 'refs/heads/3.x'
        uses: WyriHaximus/github-action-get-previous-tag@master

      - name: 'Monorepo Split of ${{ format(matrix.package, '''') }}'
        if: github.ref != 'refs/heads/3.x'
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: '${{ secrets.MACHINE_ACCESS_TOKEN }}'
        with:
          package_directory: 'ux/packages/${{ format(matrix.package, '''') }}'
          repository_organization: ferienpass
          repository_name: 'ux-${{ format(matrix.package, ''-'') }}'
          branch: 'main'
          tag: '${{ steps.previous_tag.outputs.tag }}'
          user_name: github-actions
          user_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: 'Monorepo Split of ${{ format(matrix.package, '''') }}'
        if: github.ref == 'refs/heads/3.x'
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: '${{ secrets.MACHINE_ACCESS_TOKEN }}'
        with:
          package_directory: 'ux/packages/${{ format(matrix.package, '''') }}'
          repository_organization: ferienpass
          repository_name: 'ux-${{ format(matrix.package, ''-'') }}'
          branch: 'main'
          user_name: github-actions
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
