name: Monorepo Split

on:
  push:
    tags:
      - '*'
    branches:
      - 4.x

jobs:
  monorepo-split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - base
          - backup-sftp-bundle
          - core-bundle
          - admin-bundle
          - deployer-recipes

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: previous_tag
        if: github.ref != 'refs/heads/4.x'
        uses: WyriHaximus/github-action-get-previous-tag@master

      - name: 'Monorepo Split of ${{ matrix.package }}'
        if: github.ref != 'refs/heads/4.x'
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: '${{ secrets.MACHINE_ACCESS_TOKEN }}'
        with:
          package_directory: '${{ matrix.package }}'
          repository_organization: ferienpass
          repository_name: '${{ matrix.package }}'
          branch: 'main'
          tag: '${{ steps.previous_tag.outputs.tag }}'
          user_name: github-actions
          user_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: 'Monorepo Split of ${{ matrix.package }}'
        if: github.ref == 'refs/heads/4.x'
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: '${{ secrets.MACHINE_ACCESS_TOKEN }}'
        with:
          package_directory: '${{ matrix.package }}'
          repository_organization: ferienpass
          repository_name: '${{ matrix.package }}'
          branch: 'main'
          user_name: github-actions
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
